# 🔴 Task 21-> Linear algebra and calculus in NumPy

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# LINEAR ALGEBRA

Matrix Creation and Manipulation
1. Create various types of matrices (zero matrix, identity matrix, random matrix).
2. Perform basic matrix operations (addition, subtraction, multiplication).
3Transpose a matrix and find the determinant and inverse of a matrix.


In [11]:
zero_matrix = np.zeros((3, 3))
print("Zero Matrix:\n", zero_matrix)

Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
matrix=np.zeros((4,5))
print("the zero matrix is : \n" , matrix)

the zero matrix is : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
identity_matrix = np.identity(4)
print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
identity_matrix = np.identity(2)
print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1. 0.]
 [0. 1.]]


In [13]:
random_matrix = np.random.rand(2, 3)
print("Random Matrix:\n", random_matrix)

Random Matrix:
 [[0.75661509 0.18897388 0.59382046]
 [0.21810818 0.72338066 0.65652811]]


In [24]:
#(they must have the same shape):
array1 = np.random.rand(5,5)
array2=np.random.rand(5,5)
addition = array1 + array2
print("the addition is:\n" , addition)



the addition is:
 [[0.99053955 1.45328882 1.37979111 0.93642447 0.79765742]
 [1.40144217 0.56174771 0.45646249 1.41191474 1.09729676]
 [1.32129626 1.00189455 0.21744203 0.95540946 0.62813532]
 [1.65691111 0.94719966 0.89866455 1.41678288 0.53189923]
 [0.44930945 1.34316814 1.01172636 0.55362971 1.61847837]]


In [29]:
array1 = np.random.randint(1,45,(4,5))
print(array1)
array2=np.random.randint(2,66,(4,5))
print(array2)
addition = array1 + array2
print("the addition is:\n" , addition)

[[ 9 28 32 32 12]
 [13 24 11 20 21]
 [38 39 22 10 38]
 [41  5 41  6 35]]
[[25 20 33 23  4]
 [36 19 46  9 24]
 [65 27 32 17 54]
 [ 3 51 43  8 19]]
the addition is:
 [[ 34  48  65  55  16]
 [ 49  43  57  29  45]
 [103  66  54  27  92]
 [ 44  56  84  14  54]]


In [33]:
a=np.random.randint(1,10,(3,2))
b=np.random.randint(2,80,(2,3))

product= np.dot(a,b)
print("Matrix Multiplication:\n", product)

Matrix Multiplication:
 [[213 327 179]
 [216 363 198]
 [414 510 282]]


In [38]:
#Original Matrix:
#[[1 2 3]
#[4 5 6]]
#Transposed Matrix:
#[[1 4]
#[2 5]
#[3 6]]


matrix = np.random.randint(2,90,(4,5))
print("the original matrix is:\n", matrix)

# Transpose of matriz
transpose_matrix = matrix.T
print("Transpose of Matrix E:\n", transpose_matrix)

the original matrix is:
 [[85 17 21 86 86]
 [71 40 14 88  5]
 [ 8  9  4 56 74]
 [16 76 85 64 31]]
Transpose of Matrix E:
 [[85 71  8 16]
 [17 40  9 76]
 [21 14  4 85]
 [86 88 56 64]
 [86  5 74 31]]


In [47]:
matrix = np.random.randint(2,90,(3,3))
matrix2=np.array([[2,3],[4,5]])
print("the original matrix is:\n", matrix)
print("the original matrix is:\n", matrix2)


# Determinant of matrix 
determinant_matrix = np.linalg.det(matrix)
print("Determinant of Matrix :", determinant_matrix)
determinant_matrix2 = np.linalg.det(matrix2)

print("Determinant of Matrix 2 :", determinant_matrix2)

# Inverse of matrix 
inverse_matrix= np.linalg.inv(matrix)
print("Inverse of Matrix :\n", inverse_matrix)

inverse_matrix2= np.linalg.inv(matrix2)
print("Inverse of Matrix 2 :\n", inverse_matrix2)

the original matrix is:
 [[10 82 65]
 [66 49 57]
 [30 37 37]]
the original matrix is:
 [[2 3]
 [4 5]]
Determinant of Matrix : 196.00000000000497
Determinant of Matrix 2 : -2.0
Inverse of Matrix :
 [[ -1.51020408  -3.20918367   7.59693878]
 [ -3.73469388  -8.06122449  18.97959184]
 [  4.95918367  10.66326531 -25.1122449 ]]
Inverse of Matrix 2 :
 [[-2.5  1.5]
 [ 2.  -1. ]]


Solving Linear Equations
1. Use NumPy to solve a system of linear equations.
2. Implement matrix factorization methods (LU decomposition, QR decomposition).


In [49]:
matrix = np.random.randint(1, 35, size=(4, 4))
print("Random Matrix A:\n", matrix)

solutions = np.random.randint(1, 10, size=4)
print("Random Constants vector b:\n", solutions)

linear=np.linalg.solve(matrix, solutions)
print("the solution is :/n" , linear)


Random Matrix A:
 [[27 21 31 11]
 [ 5 24 11  7]
 [23 26 17  4]
 [23 19 10 11]]
Random Constants vector b:
 [2 6 7 9]
the solution is :/n [ 0.18837867  0.33135529 -0.40077263  0.21629695]


In [62]:
matrix = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])
print(matrix)
P, L, U = np.linalg.lu(A)

print("Matrix L (Lower triangular matrix):\n", L)
print("Matrix U (Upper triangular matrix):\n", U)


[[ 2  1 -1]
 [-3 -1  2]
 [-2  1  2]]


AttributeError: module 'numpy.linalg' has no attribute 'lu'

In [63]:
Q, R = np.linalg.qr(matrix)

print("Matrix Q (Orthogonal matrix):\n", Q)
print("Matrix R (Upper triangular matrix):\n", R)

Matrix Q (Orthogonal matrix):
 [[-0.48507125  0.41166465  0.77151675]
 [ 0.72760688 -0.29939248  0.6172134 ]
 [ 0.48507125  0.86075337 -0.15430335]]
Matrix R (Upper triangular matrix):
 [[-4.12310563 -0.72760688  2.9104275 ]
 [ 0.          1.5718105   0.71105713]
 [ 0.          0.          0.15430335]]


Eigenvalues and Eigenvectors:
Eigenvalues: For a square matrix 
𝐴
A, an eigenvalue 
𝜆
λ and its corresponding eigenvector 
𝑣
v satisfy the equation:

𝐴
𝑣
=
𝜆
𝑣
Av=λv
Here, 
𝑣
v is the eigenvector and 
𝜆
λ is the eigenvalue associated with that eigenvector.

Eigenvectors: Eigenvectors are non-zero vectors that only change in magnitude (scale) when a linear transformation (represented by matrix 
𝐴
A) is applied to them. They point in the direction of greatest elongation or compression by the transformation.

In [69]:
matrix = np.random.randint(10,90,(3,3))
print(matrix)


eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

[[84 37 83]
 [49 80 34]
 [14 87 50]]
Eigenvalues:
 [170.82722898 +0.j          21.58638551+33.85178163j
  21.58638551-33.85178163j]
Eigenvectors:
 [[ 0.68788164+0.j          0.69448871+0.j          0.69448871-0.j        ]
 [ 0.54888194+0.j         -0.12526985-0.32066678j -0.12526985+0.32066678j]
 [ 0.47491838+0.j         -0.46639236+0.426197j   -0.46639236-0.426197j  ]]


In [70]:

Lambda = np.diag(eigenvalues) 
V = eigenvectors               

reconstructed_matrix = V @ Lambda @ np.linalg.inv(V)

print("Original Matrix :\n", A)
print("Reconstructed Matrix :\n", reconstructed_matrix)

Original Matrix :
 [[ 2  1 -1]
 [-3 -1  2]
 [-2  1  2]]
Reconstructed Matrix :
 [[84.-5.04497848e-16j 37.+1.65810223e-15j 83.-1.62669033e-14j]
 [49.+1.22193400e-15j 80.-1.57632905e-15j 34.-1.49734295e-14j]
 [14.+4.58350737e-16j 87.-1.42744316e-16j 50.-1.46049309e-14j]]


In [71]:
#Vector Operations
# Perform basic vector operations (addition, dot product, cross product).
# Normalize a vector and compute vector norms.


v3 = np.array([1, 7, 8])
v4 = np.array([0, 9, 9])

# Cross product of vectors
cross_product = np.cross(v3, v4)

print("Vector 3:", v3)
print("Vector 4:", v4)
print("Cross Product:", cross_product)

Vector 3: [1 7 8]
Vector 4: [0 9 9]
Cross Product: [-9 -9  9]


In [72]:
v5 = np.array([6, 4, 0])


norm_v5 = np.linalg.norm(v5)  
normalized_v5 = v5 / norm_v5  

print("Vector 5:", v5)
print("Normalized Vector 5:", normalized_v5)

Vector 5: [6 4 0]
Normalized Vector 5: [0.83205029 0.5547002  0.        ]


In [74]:
v1= np.array([6, 4, 0])
norm_v1 = np.linalg.norm(v1)

print("Vector 1:", v1)
print("Norm of Vector 1:", norm_v1)

Vector 1: [6 4 0]
Norm of Vector 1: 7.211102550927978


In [78]:
# used chatgpt
array = np.random.randint(1,10,(4, 3))

# Centering the data
mean_array = np.mean(array, axis=0)
centered_array= array - mean_array


U, S, Vt = np.linalg.svd(centered_array)

k = 2
principal_components = Vt[:k, :]
projected_data = np.dot(centered_array, principal_components.T)

print("Original Data X:\n", array)
print("\nCentered Data:\n", centered_array)
print("\nPrincipal Components:\n", principal_components)
print("\nProjected Data (Reduced Dimensionality):\n", projected_data)

Original Data X:
 [[5 4 5]
 [3 5 2]
 [2 9 3]
 [9 2 2]]

Centered Data:
 [[ 0.25 -1.    2.  ]
 [-1.75  0.   -1.  ]
 [-2.75  4.    0.  ]
 [ 4.25 -3.   -1.  ]]

Principal Components:
 [[-0.72667751  0.68536982  0.04698939]
 [-0.12533519 -0.19951955  0.97184517]]

Projected Data (Reduced Dimensionality):
 [[-0.77306041  2.1118761 ]
 [ 1.22469625 -0.75250859]
 [ 4.73984244 -0.45340643]
 [-5.19147828 -0.90596108]]


Calculus Tasks
1. Numerical Differentiation
- Use NumPy to compute the numerical derivative of a given function.
- Implement forward, backward, and central difference methods for differentiation.


In [81]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([0.1, 0.2, 0.3, 0.4])
def forward_difference(x, h=1e-5):
    return (np.roll(x, -1) - x) / h

def backward_difference(x, h=1e-5):
    return (x - np.roll(x, 1)) / h

def central_difference(x, h=1e-5):
    return (np.roll(x, -1) - np.roll(x, 1)) / (2 * h)

forward1 = forward_difference(array1)
backward1 = backward_difference(array1)
central1 = central_difference(array1)
forward2 = forward_difference(array2)
backward2 = backward_difference(array2)
central2 = central_difference(array2)
print("Array 1:", array1)
print("Forward Difference Derivatives (Array 1):", forward1)
print("Backward Difference Derivatives (Array 1):", backward1)
print("Central Difference Derivatives (Array 1):", central1)
print("Array 2:", array2)
print("Forward Difference Derivatives (Array 1):", forward2)
print("Backward Difference Derivatives (Array 1):", backward2)
print("Central Difference Derivatives (Array 1):", central2)


Array 1: [1 2 3 4]
Forward Difference Derivatives (Array 1): [ 100000.  100000.  100000. -300000.]
Backward Difference Derivatives (Array 1): [-300000.  100000.  100000.  100000.]
Central Difference Derivatives (Array 1): [-100000.  100000.  100000. -100000.]
Array 2: [0.1 0.2 0.3 0.4]
Forward Difference Derivatives (Array 1): [ 10000.  10000.  10000. -30000.]
Backward Difference Derivatives (Array 1): [-30000.  10000.  10000.  10000.]
Central Difference Derivatives (Array 1): [-10000.  10000.  10000. -10000.]


In [83]:
def f(x):
    return x**2


In [85]:
a = 0  # setting integration limits
b = 1
N = 1000# integration points/higher; the better the accuracy
def trapezoidal_rule(f, a, b, N):
    x = np.linspace(a, b, N)
    y = f(x)
    h = (b - a) / N
    integral = h * (np.sum(y) - 0.5 * (y[0] + y[-1]))
    return integral

def simpsons_rule(f, a, b, N):
    x = np.linspace(a, b, N)
    y = f(x)
    h = (b - a) / (N - 1)
    integral = h/3 * (y[0] + 4*np.sum(y[1:N-1:2]) + 2*np.sum(y[2:N-2:2]) + y[N-1])
    return integral

# Trapezoidal Rule
integral_trap = trapezoidal_rule(f, a, b, N)
print("Integral using Trapezoidal Rule:", integral_trap)

# Simpson's Rule
integral_simpson = simpsons_rule(f, a, b, N)
print("Integral using Simpson's Rule:", integral_simpson)



Integral using Trapezoidal Rule: 0.33300016683350014
Integral using Simpson's Rule: 0.33233400166866833


1. Partial Derivatives
- Basics:
- Partial derivatives involve calculating the rate of change of a function with respect to one of its variables, while keeping the other variables constant.

In [88]:
def f(x, y):
    return x**2 + 2*y

In [89]:
x0, y0 = 1, 2  


df_dx = np.gradient(f(np.array([x0, x0]), np.array([y0, y0])), np.array([x0, x0]))
df_dy = np.gradient(f(np.array([x0, x0]), np.array([y0, y0])), np.array([y0, y0]))

print("Partial derivative with respect to x:", df_dx[0])
print("Partial derivative with respect to y:", df_dy[1])

Partial derivative with respect to x: nan
Partial derivative with respect to y: nan


In [ ]:
def objective(x, y):
    return x**2 + y**2

# Example constraint: g(x, y) = x + y - 1 <= 0
def constraint(x, y):
    return x + y - 1