# 🔴 Task 11: NumPy advanced operations (indexing, slicing, broadcasting)


## Indexing and Slicing



In [1]:
import numpy as np

In [13]:
array1=np.arange(1,9)
print(array1)
print(array1[2:5])
print(array1[6:])#6 not included
print(array1[-5:-1])#not including the last thing
print(array1[0:6:2])
print(array1[1:7:3])


[1 2 3 4 5 6 7 8]
[3 4 5]
[7 8]
[4 5 6 7]
[1 3 5]
[2 5]


In [26]:
# Given a 2D array of shape (5, 5), extract a 3x3 sub-array starting from the element at position (1, 1).
array1=np.random.randint(1,25,(5,5))
print(array1)
print(array1[2,4])# row second, item 4
print(array1[1:4,1:4])# starting from  row to row 3 and , strating 1:1 to 3,4






[[ 5 18 10 21 13]
 [ 2 21 23 24 19]
 [ 3 23 14 12  4]
 [15  2 19 15  5]
 [12  1 14  7  8]]
4
[[21 23 24]
 [23 14 12]
 [ 2 19 15]]


In [53]:
#From a 3D array of shape (4, 3, 2), extract all elements in the first two rows and all columns of the second slice along the third axis.
array1=np.random.randint(1,10,(4,3,2))
print(array1)
print("slicing")
rows=array1[0:2,0:3,1:2]
print(rows)


[[[3 6]
  [1 9]
  [5 1]]

 [[1 1]
  [7 9]
  [3 9]]

 [[7 1]
  [4 2]
  [9 6]]

 [[2 8]
  [1 4]
  [4 4]]]
slicing
[[[6]
  [9]
  [1]]

 [[1]
  [9]
  [9]]]


In [67]:
#Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 7].
array=np.arange(1,25)
print(array)
print(array[1])
print(array[3])
print(array[4])
print(array[7])
print(array[1:9:2])
print(array[1:19:2])

positions=[1,3,4,7]
print(array[positions])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
2
4
5
8
[2 4 6 8]
[ 2  4  6  8 10 12 14 16 18]
[2 4 5 8]


In [100]:
#Given a 2D array, use fancy indexing to select rows [0, 2, 3] and columns [1, 3].
array=np.random.randint(1,30,(5,6))
print(array)
array2=(array[0:4,1:4])
print(array2)
array3=(array2[0:4,0:4:2])
print(array3)


rows=[0,2,3]
columns=[1,3]
print(array3[np.ix_(rows)])
print("Given a 2D array, use fancy indexing to select rows [0, 2, 3] and columns [1, 3].")
print(array[np.ix_(rows,columns)])




[[13 26 18 13 27 17]
 [ 6 22  2 25 11 21]
 [13 20  4 26 16 11]
 [14 16 13 27 16 22]
 [10 11  1  8  3 11]]
[[26 18 13]
 [22  2 25]
 [20  4 26]
 [16 13 27]]
[[26 13]
 [22 25]
 [20 26]
 [16 27]]
[[26 13]
 [20 26]
 [16 27]]
Given a 2D array, use fancy indexing to select rows [0, 2, 3] and columns [1, 3].
[[26 13]
 [20 26]
 [16 27]]


In [105]:
#From a 1D array of random integers, extract all elements that are greater than 10.
array=np.random.randint(0,40,(3,5))
print(array)
list1=[]
for rows in array:
    for columns in rows:
        if columns>10:
            list1.append(int(columns))
print(list1)

[[37  6  3 34  9]
 [24 31 39 10 22]
 [12 30 15 21 28]]
[37, 34, 24, 31, 39, 22, 12, 30, 15, 21, 28]


In [125]:
#Given a 2D array of shape (5, 5), replace all elements greater than 15 with the value 0.
array=np.random.randint(0,45,(5,5))
print(array)

for rows in range(5):
    for columns in range(5):
        if array[rows,columns]>15:#need to get the reference of the index where that element is
            array[rows,columns]=0
print("modified array: ")
print(array)
        



        


[[11  7 18 19 15]
 [36 31 29 19 20]
 [10  8 30  2 25]
 [11 37 41  1 19]
 [39 12  5 20  8]]
modified array: 
[[11  7  0  0 15]
 [ 0  0  0  0  0]
 [10  8  0  2  0]
 [11  0  0  1  0]
 [ 0 12  5  0  8]]


## Broadcasting
Broadcasting Rules:
If the arrays do not have the same rank, prepend the shape of the smaller-rank array with ones until both shapes have the same length.
The size of the output array is the maximum size along each dimension of the input arrays.
Arrays are compatible for broadcasting if, for each dimension, the axis sizes either match or one of them is 1.

In [128]:
#Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3).
# for addition, both the shapes should be in the same dimension
array1=np.random.randint(1,20,3)#1 by 3(contains one)
array2=np.random.randint(1,35,(4,3))# 4 by 3
print(array1)
print(array2)
print(array1+array2)


[17 14  6]
[[12 11 33]
 [ 8 12 23]
 [14 28 34]
 [27 23 28]]
[[29 25 39]
 [25 26 29]
 [31 42 40]
 [44 37 34]]


In [133]:
#Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,).
array=np.random.randint(1,50,(3,3))
array1=np.random.randint(1,50,3)
print(array)
print(array1)
print(array*array1)

[[18  2  4]
 [43 32 33]
 [46 23 15]]
[31 43 11]
[[ 558   86   44]
 [1333 1376  363]
 [1426  989  165]]


In [136]:
#Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.
array=np.random.randint(1,35,(2,3,4))
print("3D ARRAY: ")
print(array)
array2=np.random.randint(1,50,(3,4))
print("2D ARRAY: ")
print(array2)
print("THE RESULT IS: ")
print(array+array2)

3D ARRAY: 
[[[17 29 24 19]
  [19 23  5 10]
  [12 21 26 12]]

 [[ 6 23 11  7]
  [ 4 17 34 11]
  [32 34  5 28]]]
2D ARRAY: 
[[34 28 29 18]
 [ 6 30 27 40]
 [37 14 24 34]]
THE RESULT IS: 
[[[51 57 53 37]
  [25 53 32 50]
  [49 35 50 46]]

 [[40 51 40 25]
  [10 47 61 51]
  [69 48 29 62]]]


### Some more


In [169]:
#Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.
array=np.random.randint(1,100,(4,5))
print("THE 2D ARRAY IS:" )
print(array)
array1=np.random.randint(1,100,(5))
print("THE 1D ARRAY IS: ")
print(array1)


print("every second row and every second col")
print(array[1:4:2,1:4:2])
array2=array[1:4:2,1:4:2]
print("addition")
for row in array2:
    for col in row:
        add=col+array1
print(add)
        
   




THE 2D ARRAY IS:
[[30 58 64 23 39]
 [33 41 17 89 80]
 [21 92 29 61  4]
 [ 7 26 64 44 35]]
THE 1D ARRAY IS: 
[23  5  8 77 35]
every second row and every second col
[[41 89]
 [26 44]]
addition
[ 67  49  52 121  79]


In [174]:
#From a 3D array of shape (4, 3, 2), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.
array=np.random.randint(1,50,(4,3,2))
print("3d array is: ")
print(array)
array2=array[1:2:3]
print("the sliced array")
print(array2)
print("2d array is: ")
array5=np.random.randint(1,59,(3,2))
print("the substraction result is: ")
print(array5-array2)


3d array is: 
[[[29 41]
  [ 2 31]
  [23 17]]

 [[37 19]
  [ 4 14]
  [19 28]]

 [[24 40]
  [20 19]
  [15 44]]

 [[24 26]
  [24 47]
  [46 13]]]
the sliced array
[[[37 19]
  [ 4 14]
  [19 28]]]
2d array is: 
the substraction result is: 
[[[ -4 -11]
  [ 42  41]
  [ 13 -10]]]


In [222]:
#Given a 2D array, extract the diagonal elements and create a 1D array.
print("2D array is: ")
array1=np.random.randint(1,60,(5,5))
print(array1)
print(array1.shape)
print(array1[0])
array4=[]
col=0
rows=0

for col in range(0,5,1):
    number=array1[rows,col]
    array4.append(int(str(number)))
    rows+=1
print("the diagnol elements are: ")
print(array4)
    

2D array is: 
[[56 38 52 32  7]
 [44 34 28 13 14]
 [ 3 25 35  9 55]
 [33 55 13 57 56]
 [48 42  9 59  7]]
(5, 5)
[56 38 52 32  7]
the diagnol elements are: 
[56, 34, 35, 57, 7]


In [283]:
#Use slicing to reverse the order of elements in each row of a 2D array.
print("2D array is: ")
array1=np.random.randint(1,60,(3,5))
print(array1)
index=0
newarray=np.empty_like(array1)
# reversed_row = array[0, ::-1]#(used chat gp to figure this out)
for rows in array1:
    newarray[index]=rows[::-1]
    index+=1
print("newarray")
print(newarray)
    
   
    
    
    
    
   


2D array is: 
[[37 11 40  2 20]
 [43 48 28 30 20]
 [25 23 24  5 34]]
newarray
[[20  2 40 11 37]
 [20 30 28 48 43]
 [34  5 24 23 25]]


In [307]:
#Given a 3D array of shape (4, 5, 6), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.
array=np.random.randint(1,50,(4,5,6))
print("3d array is: ")
print(array)
array2=np.random.randint(1,64,4)
print("1D array is: ")
print(array2)
#extracting
print("extracting a sub-array of shape (2, 3, 4) ")
new_array=array[0:2,1:4,1:5]

print(new_array)
print("addition")
print(new_array+array2)


3d array is: 
[[[36 39 12 24 44 45]
  [34 43 26 48 17  8]
  [25 42 33 47 12  8]
  [ 8  7 11 27 32 14]
  [26 39 47 16 36 18]]

 [[38 32 38 40 43 41]
  [ 8 16 24 32 37 17]
  [49 32 22 28 30  8]
  [38  3  5 22 15  5]
  [ 5 11 10 36 27 46]]

 [[ 4  6 47 33 34 32]
  [39 49 24 24  5 17]
  [ 3 29 33 16 36 29]
  [26 40  2 44 37 14]
  [ 1 37 17 32  6 11]]

 [[22 24 38 28 43 18]
  [38  6  3 41  8 42]
  [26 22 40 20 35 23]
  [ 8 38 21  5  4 15]
  [11 40  7 35 10 38]]]
1D array is: 
[28 27 32 30]
extracting a sub-array of shape (2, 3, 4) 
[[[43 26 48 17]
  [42 33 47 12]
  [ 7 11 27 32]]

 [[16 24 32 37]
  [32 22 28 30]
  [ 3  5 22 15]]]
addition
[[[71 53 80 47]
  [70 60 79 42]
  [35 38 59 62]]

 [[44 51 64 67]
  [60 49 60 60]
  [31 32 54 45]]]


In [338]:
#Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.
print("2D array is: ")
array1=np.random.randint(1,60,(4,4))
print(array1)

#first two columns
first=array1[0:5,0:2]
print("the first two columns are")
print(first)

list1=first[0:5,0:1]
print(list1)
list2=first[0:5,1:2]
print(list2)

print("adding these lists")
add=list1+list2
print(add)


last_col=array1[0:5,3:4]
print(last_col)

print("setting the last col to sum of the first two cols")
array1[0:5,3:4]=add

print(arra



        
    

2D array is: 
[[44 35 39 54]
 [20 45 57 18]
 [53 36  7 14]
 [46 22  2 35]]
the first two columns are
[[44 35]
 [20 45]
 [53 36]
 [46 22]]
[[44]
 [20]
 [53]
 [46]]
[[35]
 [45]
 [36]
 [22]]
adding these lists
[[79]
 [65]
 [89]
 [68]]
[[54]
 [18]
 [14]
 [35]]


In [329]:
import numpy as np

# Generate a random 4x4 array
array1 = np.random.randint(1, 60, (4, 4))
print("Original array:")
print(array1)

# Extracting first two columns
first_two_columns = array1[:, 0:2]
print("First two columns:")
print(first_two_columns)

# Extracting last column
last_column = array1[:, 3]
print("Last column:")
print(last_column)

# Splitting the last column into two lists
list1 = last_column[0:4]
list2 = last_column[0:4]
print("List 1 (first half of last column):")
print(list1)
print("List 2 (second half of last column):")
print(list2)

# Perform element-wise addition (assuming you want to add corresponding elements of list1 and list2)
add_list = list1 + list2
print("Element-wise addition of lists:")
print(add_list)

# Assigning the result back to the original array
array1[:, 3] = add_list
print("Modified array with updated last column:")
print(array1)


Original array:
[[10 36 40 51]
 [56 34  7  1]
 [40 44 44 42]
 [42 56 53 46]]
First two columns:
[[10 36]
 [56 34]
 [40 44]
 [42 56]]
Last column:
[51  1 42 46]
List 1 (first half of last column):
[51  1 42 46]
List 2 (second half of last column):
[51  1 42 46]
Element-wise addition of lists:
[102   2  84  92]
Modified array with updated last column:
[[ 10  36  40 102]
 [ 56  34   7   2]
 [ 40  44  44  84]
 [ 42  56  53  92]]
