# INTRO TO NUMPY

In [2]:
import numpy as np

numpy= numerical python

ndarray= n dimensional array

In [7]:
np1=np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)
type(np1)
type(np1[1])

[0 1 2 3 4 5 6 7 8 9]


numpy.int64

In [8]:
np1.shape# list down all the elements

(10,)

In [17]:
# step
np2=np.arange(10)
print(np2)



np3=np.arange(0,10,2)
print("the even number are: ")
print(np3)

np4=np.arange(1,20,2)
print("odd numbers are: ")
print(np4)

[0 1 2 3 4 5 6 7 8 9]
the even number are: 
[0 2 4 6 8]
odd numbers are: 
[ 1  3  5  7  9 11 13 15 17 19]


In [20]:
np5=np.zeros(10)
print(np5)
type(np5[0])


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


numpy.float64

In [21]:
# MULTIDIMENTIONAL ZEROS
np6=np.zeros((2,10)) # ((2: dimensions, 10: elements in each dimesnions))
print(np6)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [33]:
np8=np.random.randint(1,21,21)
# random.randint(1:inclusive, 21:exclusive, 21 size)
np7=np.full((2,21), np8)
print(np7)


[[ 9  3 12  1 11 18 19  3  9 15 17  3  3  7  6 16 12 12 13 10 10]
 [ 9  3 12  1 11 18 19  3  9 15 17  3  3  7  6 16 12 12 13 10 10]]


In [43]:
np9=np.random.randint(1,20,10)
if np.all(np9 % 2 == 0):
    np10=np.full((2,10),np9)
    print(np10)
else:
    print("some elements are odd as well")
    print(np9)

z=np.random.randint(1,10,5)
if np.all( z % 5 ==0):
    print(z)
else:
    ("some are not the multipes of 5")
    print(z)




some elements are odd as well
[19 15  3 12 12  4 14  8  5 10]
[7 3 7 7 9]


In [46]:
y=np.arange(1,16,2)
x=np.array([0,4,7,8,9,67,23,24])
print(x+y)

[ 1  7 12 15 18 78 36 39]


In [62]:
# Generate a 3x2 array of random integers between 1 and 20
v=np.matrix([[1,2,3],[1,2,3]])
print(v)

[[1 2 3]
 [1 2 3]]


In [215]:
w=np.random.randint(1,21,(3,3))
m=np.random.randint(10,51,(2,3))
print(w)
print(m)
# product of 2d arrays
print("the product is: ") 
product= matrix1*matrix2
print(product)



[[12 16  1]
 [ 5  5 20]
 [10  4 13]]
[[15 22 12]
 [49 45 37]]
the product is: 
[[169 400  64]
 [169 400  64]]


In [73]:
#Create a 3D NumPy array with dimensions (2, 3, 4) filled with ones.
result=np.array([[[1,1],[1,1],[1,1]]])
print(result)

result2=np.full((3,3),1)
print(result2)

result3=np.full((3,4),1)
print(result3)



[[[1 1]
  [1 1]
  [1 1]]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [87]:
#dot multiplication of matrices
# the number of rows must match with the number of colums
var=np.array([[1,4,5],[6,7,8]])
var2=np.array([[6,9,8],[4,7,8],[3,2,1]])
result4= np.dot(var,var2)
print(result4)



[[ 37  47  45]
 [ 88 119 112]]


In [88]:
var=np.array([[1,4,5],[6,7,8]])#2by 3
var2=np.array([[6,9],[4,7],[3,2]])# 3 by 3
rows_var=var.shape[0]
colums_var2=var2.shape[1]
if rows_var==colums_var2:
    print('dot multiplication is possible')
    result4= np.dot(var,var2)
    print(result4)

else:
    print("sorry, not possible")

dot multiplication is possible
[[ 37  47]
 [ 88 119]]


In [202]:
#Calculate the mean, median, and standard deviation of a 1D array.
array1=np.arange(0,25,2)
print(array1)
fx=np.shape(array1)
print(fx)
sum=0
n=0
for x in array1:
    
    sum=sum+x
    n=n+1
    print (x)
print("the sum is: "
      +str(sum))
print(n)
mean=sum/n
print("the mean is : " + str(mean))

#median

if (n % 2 ==0):# will do floor division giving the ans 6 # %modulus function
    pos=int(n//2)
    upperbound=pos+1
    lowerbound=pos
    value=int((array1[upperbound]+array1[lowerbound])/2)
    print(value)
        
elif (n%2 != 0):
    pos=int((n)//2)
    
    print(pos)
    print(array1[pos])

# standard deviation = efx^2/ef -x^2

variance = np.sum((array1 - mean)**2) / n
          
print(np.sqrt(variance))

        



    


[ 0  2  4  6  8 10 12 14 16 18 20 22 24]
(13,)
0
2
4
6
8
10
12
14
16
18
20
22
24
the sum is: 156
13
the mean is : 12.0
6
12
7.483314773547883


In [211]:
#Find the maximum and minimum values in a 2D array.
array4=np.random.randint(1,20,(2,10))

print(array4)
size=np.shape(array4[1])
print(size)
min=float(1000)
max=float(0)
columns=1
for rows in array4:
    for elements in rows:
        if elements>max:
            max=elements
        if elements<min:
            min=elements
       
            
    
       
            
print("the max val is: " + str(max))
print(" the min val is: " + str(min))

[[ 4  2  7  7 15 19  3 16  1  5]
 [15  8  2 11  3 10  1 10 10 16]]
(10,)
the max val is: 19
 the min val is: 1


In [263]:
#Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of
num=np.random.randint(1,1000,20)
print("the original array is: ")
print(num)
mean=np.sum(num)/np.size(num)
variance=np.sum(num-mean)**2/np.size(num)
s_d=np.sqrt(variance)
if (mean==0) and  (s_d==1):
    print(num)
else:
    print("we need another array which has a sd of 1 abd mean of 0")
    num=np.random.randint(1,1000,20)
    print(num)
    
    


the original array is: 
[170 454 283 571 116 302 378 616 613 835 442 971 563 121 795 628  75 909
   3 206]
we need another array which has a sd of 1 abd mean of 0
[345 725 562 374 601 180 660 765 114 618 654 969   8 788 929 276 396 101
 263 694]


In [264]:
#Create a 2D array of shapes (5, 5) with random integers from a uniform distribution between 10 and 50.
varray2=np.random.randint(10,51,size=(5,5))
print(array2)


[[20 12 32 17]
 [31 30 13 10]
 [ 2 13 35 21]]


In [226]:
#Calculate the cumulative sum of a 1D array.
array6=np.arange(1,25)
print(array6)
sum=0
for x in array6:
    sum=sum+x
    print("the cumulative freq is: " +str(sum))


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
the cumulative freq is: 1
the cumulative freq is: 3
the cumulative freq is: 6
the cumulative freq is: 10
the cumulative freq is: 15
the cumulative freq is: 21
the cumulative freq is: 28
the cumulative freq is: 36
the cumulative freq is: 45
the cumulative freq is: 55
the cumulative freq is: 66
the cumulative freq is: 78
the cumulative freq is: 91
the cumulative freq is: 105
the cumulative freq is: 120
the cumulative freq is: 136
the cumulative freq is: 153
the cumulative freq is: 171
the cumulative freq is: 190
the cumulative freq is: 210
the cumulative freq is: 231
the cumulative freq is: 253
the cumulative freq is: 276
the cumulative freq is: 300


In [265]:
#Compute the correlation coefficient matrix of a 2D array.
#A correlation coefficient is a number between -1 and 1 that tells you the strength and direction of a relationship between variables.

# In other words, it reflects how similar the measurements of two or more variables are across a dataset.
# r= Cov(X,Y)/sd(x)*sd(y)
# ovariance (Cov): Measures how much two variables vary together. It's calculated as the average of the product of deviations of each data point from their respective means.

array1=np.random.randint(1,50,(3,4))# the shapes of the two arrays should be same
array2=np.random.randint(1,43,(3,4))

mean1=np.sum(array1)/np.size(array1)
mean2=np.sum(array2)/np.size(array2)

variance1=(np.sum(array1-mean1)**2)/np.size(array1)
sd1=np.sqrt(variance1)
variance2=(np.sum(array2-mean1)**2)/np.size(array2)
sd2=np.sqrt(variance2)

#use chat gpt to understand this
covariance = np.sum((array1 - mean1) * (array2 - mean2)) / np.size(array1)

if sd1 == 0 or sd2 == 0:
    correlation = np.nan  # Not a number
else:
    correlation = covariance / (sd1 * sd2)


print(array1)
print(array2)
print("calculating means: ")
print(mean1)
print(mean2)
print("calculating standard deviations: ")
print(sd1)
print(sd2)
print(covariance)
print("the correlation is: ")
print(correlation)

[[22 12 11 43]
 [ 4 21 11 23]
 [ 6 11 39  9]]
[[42  3 21 11]
 [30 18  2 11]
 [29 32 16 28]]
calculating means: 
17.666666666666668
20.25
calculating standard deviations: 
4.1023203976182695e-15
8.948929172439195
-37.83333333333333
the correlation is: 
-1030561608279337.6


In [258]:
#Simulate rolling a six-sided die 1000 times and count the frequency of each outcome.
dice=np.arange(1,7)
print(dice)
one=0
two=0
three=0
four=0
five=0

for i in range(1000):
    numbers=np.random.choice(dice)
    if numbers==1:
        one=one+1
         
    elif numbers==2:
        two=two+1
           
    elif numbers==3:
        three=three+1
         
    elif numbers==4:
        four=four+1
     
    elif numbers==5:
        five=five+1
    
        
  
            
print("the frequency of one is: " + str(one))
print("the frequency of two is: " + str(two))
print("the frequency of three is: " +str(three))
print("the frequency of three is: " +str(four))
print("the frequency of three is: " +str(five))

[1 2 3 4 5 6]
the frequency of one is: 195
the frequency of two is: 152
the frequency of three is: 150
the frequency of three is: 156
the frequency of three is: 201
